package dev.aurakai.auraframefx.models

import kotlinx.serialization.Serializable

/**
 * Detailed theme configuration generated by Aura
 */
@Serializable
data class ThemeConfiguration(
    val primaryColor: String,
    val secondaryColor: String,
    val backgroundColor: String,
    val textColor: String,
    val style: String
)
