package dev.aurakai.auraframefx.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.time.OffsetDateTime

/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
/**
 * A single log entry from the system.
 *
 * @param timestamp
 * @param level
 * @param tag
 * @param message
 */
@Serializable

data class LogEntry(

    @Contextual @SerialName(value = "timestamp")
    val timestamp: OffsetDateTime,

    @SerialName(value = "level")
    val level: Level,

    @SerialName(value = "tag")
    val tag: String,

    @SerialName(value = "message")
    val message: String,

    ) {

    /**
     *
     *
     * Values: DEBUG,INFO,WARN,ERROR
     */
    @Serializable
    enum class Level(val value: String) {
        @SerialName(value = "DEBUG")
        DEBUG("DEBUG"),

        @SerialName(value = "INFO")
        INFO("INFO"),

        @SerialName(value = "WARN")
        WARN("WARN"),

        @SerialName(value = "ERROR")
        ERROR("ERROR");
    }

}
