/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.aura.animations


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param enabled
 * @param animationType Type of animation effect to apply
 */
@Serializable

data class LockScreenConfigAnimation(

    @SerialName(value = "enabled")
    val enabled: Boolean? = null,

    /* Type of animation effect to apply */
    @SerialName(value = "animationType")
    val animationType: AnimationType? = null,

    ) : HashMap<String, Any>() {

    /**
     * Type of animation effect to apply
     *
     * Values: Fade,Slide,Zoom
     */
    @Serializable
    enum class AnimationType(val value: String) {
        @SerialName(value = "Fade")
        Fade("Fade"),

        @SerialName(value = "Slide")
        Slide("Slide"),

        @SerialName(value = "Zoom")
        Zoom("Zoom");
    }

}

