/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.kai


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param taskId Unique identifier for the task.
 * @param status
 * @param progress Percentage completion of the task (0-100).
 * @param result The outcome or output of the task (structure varies by taskType).
 * @param errorMessage Error message if the task failed.
 */
@Serializable

data class TaskStatus(

    /* Unique identifier for the task. */
    @SerialName(value = "taskId")
    val taskId: String,

    @SerialName(value = "status")
    val status: Status,

    /* Percentage completion of the task (0-100). */
    @SerialName(value = "progress")
    val progress: Int? = null,

    /* The outcome or output of the task (structure varies by taskType). */
    @SerialName(value = "result")
    val result: Map<String, String>? = null,

    /* Error message if the task failed. */
    @SerialName(value = "errorMessage")
    val errorMessage: String? = null,

    ) {

    /**
     *
     *
     * Values: PENDING,IN_PROGRESS,COMPLETED,FAILED,CANCELLED
     */
    @Serializable
    enum class Status(val value: String) {
        @SerialName(value = "PENDING")
        PENDING("PENDING"),

        @SerialName(value = "IN_PROGRESS")
        IN_PROGRESS("IN_PROGRESS"),

        @SerialName(value = "COMPLETED")
        COMPLETED("COMPLETED"),

        @SerialName(value = "FAILED")
        FAILED("FAILED"),

        @SerialName(value = "CANCELLED")
        CANCELLED("CANCELLED");
    }

}

