/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.kai

import dev.aurakai.auraframefx.models.AgentCapabilityCategory
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param taskType The type of task (e.g., \"CONTENT_GENERATION\", \"SYSTEM_OPTIMIZATION\", \"SECURITY_SCAN\").
 * @param agentType The AI agent responsible for the task.
 * @param details Specific parameters for the task, varying by taskType.
 * @param priority
 */
@Serializable

data class TaskScheduleRequest(

    /* The type of task (e.g., \"CONTENT_GENERATION\", \"SYSTEM_OPTIMIZATION\", \"SECURITY_SCAN\"). */
    @SerialName(value = "taskType")
    val taskType: String,

    /* The AI agent responsible for the task. */
    @Contextual @SerialName(value = "agentType")
    val agentType: AgentCapabilityCategory,

    /* Specific parameters for the task, varying by taskType. */
    @SerialName(value = "details")
    val details: Map<String, String>,

    @SerialName(value = "priority")
    val priority: Priority? = Priority.NORMAL,

    ) {

    /**
     *
     *
     * Values: HIGH,NORMAL,LOW
     */
    @Serializable
    enum class Priority(val value: String) {
        @SerialName(value = "HIGH")
        HIGH("HIGH"),

        @SerialName(value = "NORMAL")
        NORMAL("NORMAL"),

        @SerialName(value = "LOW")
        LOW("LOW");
    }

}

